modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPLv3"
[[mods]]
modId="editmobdrops"
version="1.4.1"
displayName="Edit Mob Drops"
authors="Powerthegreat"
description='''A mod for editing mob drops.'''